version: 2
registries:
  github-driesvints:
    type: git
    url: https://github.com
    password: ${{ secrets.DEPENDABOT_GH_TOKEN }}
updates:
  - package-ecosystem: "composer"
    directory: "/"
    registries: "*"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
